---
- name: Reboot required
  shell: KERNEL_NEW=$(rpm -q --last kernel |head -1 | awk '{print $1}' | sed 's/kernel-//'); KERNEL_NOW=$(uname -r); if [[ $KERNEL_NEW != $KERNEL_NOW ]]; then echo "reboot_needed"; else echo "reboot_not_needed"; fi
#command: /usr/bin/needs-restarting -r
  ignore_errors: true
  register: reboot_required
     
- name: restart system 
  command: /sbin/shutdown -r +1"Rebooting System After Patching"
  async: 0
  poll: 0
  when: reboot_required.stdout == "reboot_needed"
  register: reboot_started
  ignore_errors: true
  
- name: pause for 120 secs
  pause:
  minutes: 2

- name: wait for host boot
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    port: 22
    delay: "{{ boot_wait | default(15) }}"
    timeout: 60
    state: started
  when: reboot_started.changed
