---
- name: Reboot required
  shell: KERNEL_NEW=$(rpm -q --last kernel |head -1 | awk '{print $1}' | sed 's/kernel-//'); KERNEL_NOW=$(uname -r); if [[ $KERNEL_NEW != $KERNEL_NOW ]]; then echo "reboot_needed"; else echo "reboot_not_needed"; fi
#command: /usr/bin/needs-restarting -r
  ignore_errors: true
  register: reboot_required
     
- name: restart system 
  command: /sbin/shutdown -r +1 "Rebooting System After Patching"
  async: 30
  poll: 0
  when: reboot_required.stdout == "reboot_needed"
  register: reboot_started
  ignore_errors: true
  notify:
    - waiting for server to come back after reboot

- name: wait for ssh again available.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 60
