---
- name: Reboot required (CentOS or Red Hat) - Step 1
  command: /usr/bin/needs-restarting -r
  register: reboot_required
  ignore_errors: True

- name: restart system (CentOS or Red Hat) - Step 2
  command: shutdown -r +1 “Rebooting System After Patching”
  async: 0
  poll: 0
  when: reboot_required.stdout == “reboot_needed”
  register: reboot_started
  ignore_errors: true
  notify:
    - waiting for server to come back after reboot

- name: waiting for server to come back after reboot
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=10 timeout=60
  when: reboot_started|changed
  become: no
