---
- name: verify that client1.localdomain is up
  uri:
    url: http://{{ client1 }}/
    status_code: 200
    follow_redirects: none
    vars:
       http_headers:
         Host: client1.localdomain

- name: verify that client2.localdomain is up
  uri:
    url: http://{{ client2 }}/
    status_code: 200
    follow_redirects: none
  vars:
     http_headers:
       Host: client2.localdomain
